spring.application.name=Unit-2-Final-Project
spring.datasource.url=jdbc:mysql://localhost:3306/unit-2-final-project?useSSL=false
spring.datasource.username=root
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update